
package org.workin.test.ws.soap.service.image.small;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Dec 01 16:47:45 CST 2009
 * Generated source version: 2.2.4
 * 
 */

public final class SmallImageService_SmallImageServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.ws.workin.org", "SmallImageService");

    private SmallImageService_SmallImageServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SmallImageService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SmallImageService_Service ss = new SmallImageService_Service(wsdlURL, SERVICE_NAME);
        SmallImageService port = ss.getSmallImageServicePort();  
        
        {
        System.out.println("Invoking getImage...");
        java.lang.String _getImage_arg0 = "";
        org.workin.test.ws.soap.service.image.small.SmallImageResult _getImage__return = port.getImage(_getImage_arg0);
        System.out.println("getImage.result=" + _getImage__return);


        }
        {
        System.out.println("Invoking getImageWithPath...");
        java.lang.String _getImageWithPath_arg0 = "";
        org.workin.test.ws.soap.service.image.small.SmallImageResult _getImageWithPath__return = port.getImageWithPath(_getImageWithPath_arg0);
        System.out.println("getImageWithPath.result=" + _getImageWithPath__return);


        }

        System.exit(0);
    }

}
