
/*
 * 
 */

package org.workin.test.ws.soap.service.image.large;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Dec 01 17:21:25 CST 2009
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "LargeImageService", 
                  wsdlLocation = "http://localhost:8080/workin/soap/image/largeImageService?wsdl",
                  targetNamespace = "http://soap.ws.workin.org") 
public class LargeImageService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://soap.ws.workin.org", "LargeImageService");
    public final static QName LargeImageServicePort = new QName("http://soap.ws.workin.org", "LargeImageServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/workin/soap/image/largeImageService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/workin/soap/image/largeImageService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public LargeImageService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LargeImageService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LargeImageService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns LargeImageService
     */
    @WebEndpoint(name = "LargeImageServicePort")
    public LargeImageService getLargeImageServicePort() {
        return super.getPort(LargeImageServicePort, LargeImageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LargeImageService
     */
    @WebEndpoint(name = "LargeImageServicePort")
    public LargeImageService getLargeImageServicePort(WebServiceFeature... features) {
        return super.getPort(LargeImageServicePort, LargeImageService.class, features);
    }

}
