
/*
 * 
 */

package org.workin.test.ws.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Dec 01 17:24:37 CST 2009
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "EmployeeServiceImplService", 
                  wsdlLocation = "http://localhost:8080/workin/soap/employeeService?wsdl",
                  targetNamespace = "http://soap.ws.workin.org") 
public class EmployeeServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://soap.ws.workin.org", "EmployeeServiceImplService");
    public final static QName EmployeeServiceImplPort = new QName("http://soap.ws.workin.org", "EmployeeServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/workin/soap/employeeService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/workin/soap/employeeService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EmployeeServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns EmployeeService
     */
    @WebEndpoint(name = "EmployeeServiceImplPort")
    public EmployeeService getEmployeeServiceImplPort() {
        return super.getPort(EmployeeServiceImplPort, EmployeeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeService
     */
    @WebEndpoint(name = "EmployeeServiceImplPort")
    public EmployeeService getEmployeeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EmployeeServiceImplPort, EmployeeService.class, features);
    }

}
