
/*
 * 
 */

package org.workin.test.ws.soap.service.image.small;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Tue Dec 01 16:47:45 CST 2009
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "SmallImageService", 
                  wsdlLocation = "http://localhost:8080/workin/soap/image/smallImageService?wsdl",
                  targetNamespace = "http://soap.ws.workin.org") 
public class SmallImageService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://soap.ws.workin.org", "SmallImageService");
    public final static QName SmallImageServicePort = new QName("http://soap.ws.workin.org", "SmallImageServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/workin/soap/image/smallImageService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/workin/soap/image/smallImageService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SmallImageService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmallImageService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmallImageService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SmallImageService
     */
    @WebEndpoint(name = "SmallImageServicePort")
    public SmallImageService getSmallImageServicePort() {
        return super.getPort(SmallImageServicePort, SmallImageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmallImageService
     */
    @WebEndpoint(name = "SmallImageServicePort")
    public SmallImageService getSmallImageServicePort(WebServiceFeature... features) {
        return super.getPort(SmallImageServicePort, SmallImageService.class, features);
    }

}
